### ISSUE TITLE
DahuaHash

### ISSUE THREAD

**Issue by BrunoRoselli** [haicen/DahuaHashCreator#3]
Hi, this program cannot give hash when password contain Ñ or ñ, dahua programs permit this character.

Example: HASH: q4R9ROGy   PASS: coño

**Comment by stefantsar** [comment]
Hello there, please ping me either on linkedin or here. I would really like to talk to you :)

**Comment by brandon9vt** [comment]
@BrunoRoselli 

It is dependent on exactly what character encoding is used. I don't know what hardware you're using, but the character encoding changes the md5 has generated before being compressed for the dahua algorithm.

coño (utf-8) = f7ca33d57f9bf982099401ae20fea981
coño (Spanish, iso-8859-1) = 2d073c82cb4890ed43d069e5f41476fc

Your password appears to be ISO 8859-1, so if you change 

45 `m.update(passw.encode("ascii"))`

to `m.update(passw.encode("iso-8859-1"))`

it will generate the hash you provided

**Comment by haicen** [comment]
> Hello there, please ping me either on linkedin or here. I would really like to talk to you :)

You can email me at haicenhack@protonmail.com

I don't know who you are on linkedin, so I couldn't connect with you if I wanted to.
